#!/usr/bin/env python3
"""
analyze_all.py — One-shot complete analysis of experiment runs.

Discovers runs by condition tags, validates data, computes metrics,
generates comparison tables, plots, and a detailed markdown report.

Usage:
  python scripts/analyze_all.py --run-root runs --out reports/experiment_matrix
  python scripts/analyze_all.py --help
"""

import argparse
import csv
import json
import math
import os
import sys
from collections import defaultdict
from datetime import datetime


def discover_runs(run_root):
    """Discover all completed runs under run_root/."""
    runs = []
    if not os.path.isdir(run_root):
        return runs

    for entry in sorted(os.listdir(run_root)):
        run_dir = os.path.join(run_root, entry)
        manifest_path = os.path.join(run_dir, "manifest.json")
        metrics_path = os.path.join(run_dir, "metrics.json")
        config_path = os.path.join(run_dir, "config.resolved.json")

        if os.path.isfile(manifest_path) and os.path.isfile(metrics_path):
            try:
                with open(manifest_path) as f:
                    manifest = json.load(f)
                with open(metrics_path) as f:
                    metrics = json.load(f)
                config = {}
                if os.path.isfile(config_path):
                    with open(config_path) as f:
                        config = json.load(f)

                runs.append({
                    "run_id": entry,
                    "dir": run_dir,
                    "manifest": manifest,
                    "metrics": metrics,
                    "config": config,
                    "tag": manifest.get("tag", config.get("tag", "")),
                })
            except (json.JSONDecodeError, KeyError) as e:
                print(f"  ⚠ Skipping {entry}: malformed JSON — {e}")
    return runs


# ── Validators (Phase 6) ────────────────────────────────────

class ValidationError(Exception):
    """Structured validation error with cause and fix."""
    def __init__(self, what, cause, fix):
        self.what = what
        self.cause = cause
        self.fix = fix
        super().__init__(f"{what}: {cause}")


def validate_metrics(metrics, run_id):
    """Validate a single metrics.json for integrity."""
    errors = []

    # Required fields
    required = ["schema_version", "run_id", "total_games", "total_llm_calls",
                 "total_legal_moves", "legal_move_rate"]
    for field in required:
        if field not in metrics:
            errors.append(ValidationError(
                what=f"Missing required field '{field}' in metrics",
                cause=f"Run {run_id} metrics.json is missing '{field}'",
                fix=f"Re-run the experiment: python scripts/run_game.py --tag <tag>"
            ))

    # Value range checks
    rate = metrics.get("legal_move_rate", -1)
    if not (0 <= rate <= 1):
        errors.append(ValidationError(
            what=f"legal_move_rate={rate} out of range [0, 1]",
            cause=f"Computed rate is invalid in run {run_id}",
            fix="Check raw_outputs.jsonl for corrupted records"
        ))

    # NaN/Inf checks
    for key in ["legal_move_rate", "latency_mean_ms", "latency_median_ms"]:
        val = metrics.get(key)
        if val is not None and (isinstance(val, float) and (math.isnan(val) or math.isinf(val))):
            errors.append(ValidationError(
                what=f"{key} is NaN or Inf",
                cause=f"Numerical error in run {run_id}",
                fix="Re-run the experiment with valid data"
            ))

    # Schema version
    if metrics.get("schema_version") not in ("1.0",):
        errors.append(ValidationError(
            what=f"Unknown schema_version: {metrics.get('schema_version')}",
            cause="Metrics file was generated by an incompatible version",
            fix="Update scripts/analyze_all.py or re-run experiments"
        ))

    return errors


def validate_raw_outputs(run_dir, run_id):
    """Validate raw_outputs.jsonl for duplicates and schema."""
    errors = []
    raw_path = os.path.join(run_dir, "raw_outputs.jsonl")

    if not os.path.isfile(raw_path):
        errors.append(ValidationError(
            what="Missing raw_outputs.jsonl",
            cause=f"Run {run_id} has no raw output data",
            fix=f"Re-run: python scripts/run_game.py --tag <tag>"
        ))
        return errors

    seen_keys = set()
    line_num = 0
    required_fields = ["game_id", "turn_number", "fen", "is_legal", "fallback_used"]

    with open(raw_path) as f:
        for line in f:
            line_num += 1
            try:
                record = json.loads(line.strip())
            except json.JSONDecodeError:
                errors.append(ValidationError(
                    what=f"Malformed JSON at line {line_num}",
                    cause=f"raw_outputs.jsonl line {line_num} is not valid JSON",
                    fix="Check for truncated writes; re-run if needed"
                ))
                continue

            # Required fields
            for field in required_fields:
                if field not in record:
                    errors.append(ValidationError(
                        what=f"Missing field '{field}' at line {line_num}",
                        cause="Incomplete record in raw_outputs.jsonl",
                        fix="Re-run the experiment"
                    ))

            # Duplicate check
            key = (record.get("game_id"), record.get("turn_number"))
            if key in seen_keys:
                errors.append(ValidationError(
                    what=f"Duplicate (game_id={key[0]}, turn={key[1]})",
                    cause="Same game+turn appears twice",
                    fix="Check for double-appending; re-run if needed"
                ))
            seen_keys.add(key)

    return errors


# ── Analysis ─────────────────────────────────────────────────

def compute_comparison(runs_by_tag):
    """Compute comparison metrics across tagged conditions."""
    rows = []
    for tag, runs in sorted(runs_by_tag.items()):
        # Use the latest run for each tag
        run = runs[-1]
        m = run["metrics"]
        c = run["config"] or run["manifest"].get("config", {})

        rows.append({
            "tag": tag,
            "run_id": run["run_id"],
            "temperature": c.get("temperature", "?"),
            "constrained": c.get("constrained_decoding", "?"),
            "seed": c.get("seed", "?"),
            "model": c.get("model", "?"),
            "total_games": m.get("total_games", 0),
            "total_llm_calls": m.get("total_llm_calls", 0),
            "legal_moves": m.get("total_legal_moves", 0),
            "legal_rate": m.get("legal_move_rate", 0),
            "unique_moves": m.get("unique_moves", 0),
            "latency_mean_ms": m.get("latency_mean_ms", 0),
            "latency_median_ms": m.get("latency_median_ms", 0),
        })

    return rows


def compute_pairwise_deltas(rows):
    """Compute deltas between pairs of conditions."""
    deltas = []
    for i in range(len(rows)):
        for j in range(i + 1, len(rows)):
            a, b = rows[i], rows[j]
            delta = {
                "pair": f"{a['tag']} vs {b['tag']}",
                "legal_rate_delta": round(b["legal_rate"] - a["legal_rate"], 4),
                "legal_rate_a": a["legal_rate"],
                "legal_rate_b": b["legal_rate"],
                "latency_delta_ms": round(b["latency_mean_ms"] - a["latency_mean_ms"], 1),
                "unique_moves_delta": b["unique_moves"] - a["unique_moves"],
            }
            deltas.append(delta)
    return deltas


def generate_plots(rows, out_dir):
    """Generate comparison plots."""
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("  ⚠ matplotlib not installed — skipping plots")
        return []

    plots_dir = os.path.join(out_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)
    plot_files = []

    tags = [r["tag"] for r in rows]
    colors = ['#2196F3', '#FF9800', '#4CAF50', '#9C27B0', '#f44336']

    # ── Plot 1: Legal Move Rate ──
    fig, ax = plt.subplots(figsize=(10, 6))
    rates = [r["legal_rate"] * 100 for r in rows]
    bars = ax.bar(tags, rates, color=colors[:len(tags)], edgecolor='black', alpha=0.85, width=0.5)
    for bar, rate in zip(bars, rates):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{rate:.1f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')
    ax.set_ylim(0, 110)
    ax.set_title("Legal Move Rate by Condition", fontsize=14, fontweight='bold')
    ax.set_ylabel("Legal Move Rate (%)")
    ax.axhline(y=50, color='gray', linestyle=':', alpha=0.5, label='50% baseline')
    ax.legend()
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    plt.tight_layout()
    path = os.path.join(plots_dir, "legal_rate_comparison.png")
    plt.savefig(path, dpi=200, bbox_inches='tight')
    plt.close()
    plot_files.append(path)

    # ── Plot 2: Latency Comparison ──
    fig, ax = plt.subplots(figsize=(10, 6))
    means = [r["latency_mean_ms"] for r in rows]
    medians = [r["latency_median_ms"] for r in rows]
    x = np.arange(len(tags))
    w = 0.35
    ax.bar(x - w/2, means, w, label='Mean', color=colors[:len(tags)], alpha=0.85, edgecolor='black')
    ax.bar(x + w/2, medians, w, label='Median', color=colors[:len(tags)], alpha=0.5, edgecolor='black', hatch='///')
    ax.set_xticks(x)
    ax.set_xticklabels(tags)
    ax.set_title("Response Latency by Condition", fontsize=14, fontweight='bold')
    ax.set_ylabel("Latency (ms)")
    ax.legend()
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    plt.tight_layout()
    path = os.path.join(plots_dir, "latency_comparison.png")
    plt.savefig(path, dpi=200, bbox_inches='tight')
    plt.close()
    plot_files.append(path)

    # ── Plot 3: Move Diversity ──
    fig, ax = plt.subplots(figsize=(10, 6))
    uniq = [r["unique_moves"] for r in rows]
    ax.bar(tags, uniq, color=colors[:len(tags)], edgecolor='black', alpha=0.85, width=0.5)
    for i, (tag, u) in enumerate(zip(tags, uniq)):
        ax.text(i, u + 0.5, str(u), ha='center', va='bottom', fontsize=12, fontweight='bold')
    ax.set_title("Move Diversity (Unique Moves) by Condition", fontsize=14, fontweight='bold')
    ax.set_ylabel("Unique Moves")
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    plt.tight_layout()
    path = os.path.join(plots_dir, "move_diversity_comparison.png")
    plt.savefig(path, dpi=200, bbox_inches='tight')
    plt.close()
    plot_files.append(path)

    return plot_files


def generate_report(rows, deltas, plot_files, out_dir, all_errors):
    """Generate a detailed markdown report."""
    report_path = os.path.join(out_dir, "report.md")

    with open(report_path, "w") as f:
        f.write("# LLM Chess Engine — Experiment Matrix Report\n\n")
        f.write(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n")

        # ── Summary Table ──
        f.write("## Summary Comparison\n\n")
        f.write("| Condition | Temp | Constrained | Games | LLM Calls | Legal Rate | Unique Moves | Latency (mean) |\n")
        f.write("|:----------|:----:|:-----------:|:-----:|:---------:|:----------:|:------------:|:--------------:|\n")
        for r in rows:
            constrained = "Yes" if r["constrained"] else "No"
            f.write(f"| {r['tag']} | {r['temperature']} | {constrained} | "
                    f"{r['total_games']} | {r['total_llm_calls']} | "
                    f"**{r['legal_rate']*100:.1f}%** | {r['unique_moves']} | "
                    f"{r['latency_mean_ms']:.0f} ms |\n")

        # ── Pairwise Deltas ──
        f.write("\n## Pairwise Comparisons\n\n")
        for d in deltas:
            direction = "↑" if d["legal_rate_delta"] > 0 else "↓" if d["legal_rate_delta"] < 0 else "="
            f.write(f"### {d['pair']}\n\n")
            f.write(f"| Metric | Value |\n")
            f.write(f"|:-------|:------|\n")
            f.write(f"| Legal rate delta | {direction} {abs(d['legal_rate_delta']*100):.1f} pp "
                    f"({d['legal_rate_a']*100:.1f}% → {d['legal_rate_b']*100:.1f}%) |\n")
            f.write(f"| Latency delta | {d['latency_delta_ms']:+.0f} ms |\n")
            f.write(f"| Unique moves delta | {d['unique_moves_delta']:+d} |\n\n")

        # ── Interpretation ──
        f.write("## Interpretation\n\n")

        if len(rows) >= 2:
            # Find best legal rate
            best = max(rows, key=lambda r: r["legal_rate"])
            worst = min(rows, key=lambda r: r["legal_rate"])
            f.write(f"**Best legal move rate**: {best['tag']} at {best['legal_rate']*100:.1f}%\n\n")
            f.write(f"**Worst legal move rate**: {worst['tag']} at {worst['legal_rate']*100:.1f}%\n\n")

            # Temperature effect
            temp_groups = defaultdict(list)
            for r in rows:
                temp_groups[r["temperature"]].append(r)
            if len(temp_groups) > 1:
                f.write("### Temperature Effect\n\n")
                for temp, group in sorted(temp_groups.items()):
                    avg_rate = sum(r["legal_rate"] for r in group) / len(group)
                    f.write(f"- Temp={temp}: avg legal rate {avg_rate*100:.1f}% "
                            f"(across {len(group)} condition(s))\n")
                f.write("\n")

            # Constraint effect
            constrained_runs = [r for r in rows if r["constrained"]]
            unconstrained_runs = [r for r in rows if not r["constrained"]]
            if constrained_runs and unconstrained_runs:
                c_rate = sum(r["legal_rate"] for r in constrained_runs) / len(constrained_runs)
                u_rate = sum(r["legal_rate"] for r in unconstrained_runs) / len(unconstrained_runs)
                f.write("### Constrained Decoding Effect\n\n")
                f.write(f"- Unconstrained avg: {u_rate*100:.1f}%\n")
                f.write(f"- Constrained avg: {c_rate*100:.1f}%\n")
                f.write(f"- **Delta: {(c_rate - u_rate)*100:+.1f} percentage points**\n\n")

        # ── Plots ──
        if plot_files:
            f.write("## Visualizations\n\n")
            for pf in plot_files:
                basename = os.path.basename(pf)
                f.write(f"![{basename}](plots/{basename})\n\n")

        # ── Validation ──
        if all_errors:
            f.write("## ⚠ Validation Warnings\n\n")
            for run_id, errs in all_errors.items():
                f.write(f"### Run: {run_id}\n\n")
                for e in errs:
                    f.write(f"- **{e.what}**\n")
                    f.write(f"  - Cause: {e.cause}\n")
                    f.write(f"  - Fix: `{e.fix}`\n")
                f.write("\n")

        # ── Methodology ──
        f.write("## Methodology\n\n")
        f.write("- **Game format**: White plays random legal moves; Black plays via LLM (Ollama)\n")
        f.write("- **Fallback**: When LLM produces an illegal move, a random legal move is played\n")
        f.write("- **Seed**: Fixed per condition for reproducibility\n")
        f.write("- **Metrics**: Legal move rate = (LLM legal moves) / (total LLM calls)\n")

    return report_path


def generate_csv(rows, out_dir):
    """Generate metrics_comparison.csv."""
    csv_path = os.path.join(out_dir, "metrics_comparison.csv")
    fieldnames = ["tag", "run_id", "temperature", "constrained", "seed", "model",
                  "total_games", "total_llm_calls", "legal_moves", "legal_rate",
                  "unique_moves", "latency_mean_ms", "latency_median_ms"]

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    return csv_path


def main():
    parser = argparse.ArgumentParser(
        description="Analyze experiment matrix runs and generate comparison report.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python scripts/analyze_all.py --run-root runs --out reports/experiment_matrix
  python scripts/analyze_all.py --tags t02_unconstrained t08_unconstrained t08_constrained
""",
    )
    parser.add_argument("--run-root", default="runs",
                        help="Root directory containing run directories (default: runs)")
    parser.add_argument("--out", default="reports/experiment_matrix",
                        help="Output directory for report (default: reports/experiment_matrix)")
    parser.add_argument("--tags", nargs="*", default=None,
                        help="Filter to specific condition tags (default: all)")

    args = parser.parse_args()

    print("=" * 60)
    print("  LLM Chess Engine — Experiment Analysis")
    print("=" * 60)

    # ── Discover runs ────────────────────────────────────
    print(f"\n🔍 Scanning {args.run_root}/ for completed runs...")
    runs = discover_runs(args.run_root)

    if not runs:
        print(f"\n✗ No completed runs found in {args.run_root}/")
        print(f"  Expected structure: {args.run_root}/<RUN_ID>/manifest.json + metrics.json")
        print(f"\n  To create runs, use:")
        print(f"    python scripts/run_game.py --temperature 0.2 --seed 42 --tag t02_unconstrained")
        print(f"    bash scripts/run_experiment_matrix.sh")
        sys.exit(1)

    print(f"  Found {len(runs)} run(s)")

    # ── Group by tag ─────────────────────────────────────
    runs_by_tag = defaultdict(list)
    for run in runs:
        tag = run["tag"] or run["run_id"]
        runs_by_tag[tag].append(run)

    if args.tags:
        filtered = {t: runs_by_tag[t] for t in args.tags if t in runs_by_tag}
        missing = [t for t in args.tags if t not in runs_by_tag]
        if missing:
            print(f"\n⚠ Missing condition tags: {', '.join(missing)}")
            print(f"  Available tags: {', '.join(runs_by_tag.keys())}")
            if not filtered:
                print(f"\n✗ No matching runs found. Cannot generate report.")
                sys.exit(1)
        runs_by_tag = filtered

    for tag, tag_runs in sorted(runs_by_tag.items()):
        print(f"  [{tag}] {len(tag_runs)} run(s), latest: {tag_runs[-1]['run_id']}")

    # ── Validate ─────────────────────────────────────────
    print(f"\n📋 Validating run data...")
    all_errors = {}
    for run in runs:
        errors = validate_metrics(run["metrics"], run["run_id"])
        errors.extend(validate_raw_outputs(run["dir"], run["run_id"]))
        if errors:
            all_errors[run["run_id"]] = errors
            for e in errors:
                print(f"  ⚠ [{run['run_id']}] {e.what}")
                print(f"    Cause: {e.cause}")
                print(f"    Fix: {e.fix}")

    if not all_errors:
        print("  ✓ All runs passed validation")

    # ── Compute comparison ───────────────────────────────
    print(f"\n📊 Computing comparison metrics...")
    rows = compute_comparison(runs_by_tag)
    deltas = compute_pairwise_deltas(rows)

    # ── Generate outputs ─────────────────────────────────
    os.makedirs(args.out, exist_ok=True)

    print(f"\n📈 Generating plots...")
    plot_files = generate_plots(rows, args.out)
    print(f"  Generated {len(plot_files)} plot(s)")

    print(f"\n📝 Generating report...")
    report_path = generate_report(rows, deltas, plot_files, args.out, all_errors)
    print(f"  Report: {report_path}")

    csv_path = generate_csv(rows, args.out)
    print(f"  CSV: {csv_path}")

    # ── Final summary ────────────────────────────────────
    print(f"\n{'=' * 60}")
    print(f"  Analysis Complete")
    print(f"{'=' * 60}")
    print(f"  Conditions compared: {len(rows)}")
    print(f"  Pairwise deltas:     {len(deltas)}")
    print(f"  Plots generated:     {len(plot_files)}")
    print(f"  Output directory:    {args.out}/")
    print(f"\n  Files:")
    print(f"    {report_path}")
    print(f"    {csv_path}")
    for pf in plot_files:
        print(f"    {pf}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
